name: Build and Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t portfolio-app:${{ steps.vars.outputs.TAG }} .

      - name: Tag image for ECR
        run: |
          docker tag portfolio-app:${{ steps.vars.outputs.TAG }} \
          137068224793.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app:${{ steps.vars.outputs.TAG }}

      - name: Push image to ECR
        run: |
          docker push \
          137068224793.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app:${{ steps.vars.outputs.TAG }}

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 137068224793.dkr.ecr.eu-central-1.amazonaws.com

            docker pull 137068224793.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app:${{ steps.vars.outputs.TAG }}

            docker stop portfolio-app || true
            docker rm portfolio-app || true

            docker run -d \
              --restart unless-stopped \
              -p 8080:80 \
              --name portfolio-app \
              137068224793.dkr.ecr.eu-central-1.amazonaws.com/portfolio-app:${{ steps.vars.outputs.TAG }}